### ISSUE TITLE
restarting the stack overwrites user credential

### ISSUE THREAD

**Issue by mfuhrmann** [opennms-forge/demo.opennms.org#37]
In the current state 

`docker-compose down`
`docker-compose up -d`

doesn't trigger the create-users.sh file. So we are loosing the defined passwords.

**Comment by indigo423** [comment]
I would recommend, create the users as you need it and copy the users.xml to etc-overlay. The only other way is persist /opt/opennms/etc and migrate the persisted config on update.

**Comment by mfuhrmann** [comment]
solved with https://github.com/opennms-forge/demo.opennms.org/commit/0dd8a7c1f4f51c6d164e44697b44fa62347f4a41#diff-bddf18384a22aced202978e2884b610e
