### ISSUE TITLE
XML collector not available in Docker Image

### ISSUE THREAD

**Issue by mfuhrmann** [opennms-forge/demo.opennms.org#48]
blocks #45 

We need **opennms-plugin-protocol-xml** in the default setup. Not sure what's the best approach to add it into the docker installation.

**Comment by indigo423** [comment]
> The XML Collector is now part of the core package as of OpenNMS Horizon 20. For older releases, an additional package named opennms-plugin-protocol-xml must be installed in order to use this collector.

There is no opennms-plugin-protocol-xml in any version of Horizon 20+

See https://wiki.opennms.org/wiki/XML_Collector
