### ISSUE TITLE
Git submodule setup needs an update

### ISSUE THREAD

**Issue by mfuhrmann** [opennms-forge/demo.opennms.org#50]
Since we updated [Ubiquiti](https://github.com/opennms-config-modules/ubiquiti/commits/master) and [netsnmp](https://github.com/opennms-config-modules/net-snmp/commits/master) config modules the `git submodule --init` command doesn't provide the latest state. I guess those guys here need an update: https://github.com/opennms-forge/demo.opennms.org/tree/master/etc-overlay/config-modules

**Comment by indigo423** [comment]
Released a new minor version of Ubiquitie and Net-SNMP module and updated the repo accordingly.
