### ISSUE TITLE
Ubuntu 16.04 - docker build

### ISSUE THREAD

**Issue by rbj2000** [opennms-forge/demo.opennms.org#75]
I tried to deploy stack on Ubuntu.

Even I have correct binds:
            "Binds": [
                "/opt/demo.opennms.org/requisitions:/opt/opennms-pris/requisitions:rw",
                "/opt/demo.opennms.org/scriptsteps:/opt/opennms-pris/scriptsteps:rw"
            ],

But I can see only:
-rw-r--r-- 1 root root 21504 May 17  2017 myInventory.xls
drwxr-xr-x 2 root root  4096 Jan 28 22:07 myRouter
drwxr-xr-x 2 root root  4096 Jan 28 22:07 myServer
in docker image.

I'm using docker verion 18.09.1

Any issues with Ubuntu?

**Comment by mfuhrmann** [comment]
I'm testing on Ubuntu 18 and Docker 18.06 and it works fine.

But I'm not sure if you understand your problem. Can you please provide some more information?

**Comment by indigo423** [comment]
@rbj2000 If you have generic usability questions it would be cool to ask these type of questions in our [Community](https://opennms.discourse.group/c/community-support). You'll reach a greater audience in our community. Once we qualified it is really a problem which needs changes in the demo environment we would create an issue here.

**Comment by rbj2000** [comment]
I think it has something to do with the user under wich docker image is started.
I used sudo init.sh to build a stack and I got the folder structure as mentioned above (using docker exec -it demo-pris /bin/bash).
However I tried to build stack uder root and now I have correct (from modified requisitions folder) structure:
-rw-r--r-- 1 1000 1000 25088 Jan 28 22:41 demo-opennms-org.xls
drwxr-xr-x 2 1000 1000  4096 Jan 28 22:30 docker-compose-nodes
drwxr-xr-x 2 1000 1000  4096 Jan 28 22:30 geomap-nodes
drwxr-xr-x 2 1000 1000  4096 Jan 28 22:30 json-nodes
drwxrwxr-x 2 1000 1000  4096 Jan 28 22:39 **l2vpn-nodes**
drwxr-xr-x 2 1000 1000  4096 Jan 28 22:30 opennms-websites
drwxr-xr-x 2 1000 1000  4096 Jan 28 22:30 public-dns
